name: TPA
version: '${project.version}'
main: de.silentesc.tpa.Main
api-version: '1.20'
authors: [silentesc]
description: 1.20.1 Spigot Plugin for teleport requests with other players

commands:
  tpa:
    usage: /tpa [player]
    description: Teleport request to teleport to the player
  tpaccept:
    usage: /tpaccept [player]
    description: Accept pending teleport accept
